//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApi.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinApi.Resources.Language.SK", typeof(SK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlyhalo pripojenie k internetu.
        /// </summary>
        internal static string connectionMsg {
            get {
                return ResourceManager.GetString("connectionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status pripojenia.
        /// </summary>
        internal static string connectionTitle {
            get {
                return ResourceManager.GetString("connectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpisovanie sa nepodarilo skúste znova.
        /// </summary>
        internal static string failedSignDocument {
            get {
                return ResourceManager.GetString("failedSignDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodarilo sa uložiť dokument.
        /// </summary>
        internal static string failSavingDocument {
            get {
                return ResourceManager.GetString("failSavingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument sa nepodarilo nahrať na server.
        /// </summary>
        internal static string failUploadDocument {
            get {
                return ResourceManager.GetString("failUploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument na podpísanie bol úspešne stiahnutý.
        /// </summary>
        internal static string foundDocument {
            get {
                return ResourceManager.GetString("foundDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvojklik pre podpísanie a kliknutím pravým tlačidlom pre menu.
        /// </summary>
        internal static string iconTitleDefualt {
            get {
                return ResourceManager.GetString("iconTitleDefualt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravé prebieha podpisovanie.
        /// </summary>
        internal static string iconTitleWorking {
            get {
                return ResourceManager.GetString("iconTitleWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravé sa vykonáva podpisovanie.
        /// </summary>
        internal static string inProccesDocument {
            get {
                return ResourceManager.GetString("inProccesDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikácia stratila pripojenie k internetu.
        /// </summary>
        internal static string lostConnection {
            get {
                return ResourceManager.GetString("lostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenašiel sa žiadny dokument na podpisanie.
        /// </summary>
        internal static string notFoundDocument {
            get {
                return ResourceManager.GetString("notFoundDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikácia  je pripojena k internetu.
        /// </summary>
        internal static string onlineConnection {
            get {
                return ResourceManager.GetString("onlineConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukladám dokument.
        /// </summary>
        internal static string savingDocument {
            get {
                return ResourceManager.GetString("savingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hľadám nový dokument na podpísanie.
        /// </summary>
        internal static string searchDocument {
            get {
                return ResourceManager.GetString("searchDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpisovanie.
        /// </summary>
        internal static string signatureTitle {
            get {
                return ResourceManager.GetString("signatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spúšťam aplikáciu na podpísanie.
        /// </summary>
        internal static string startSignDocument {
            get {
                return ResourceManager.GetString("startSignDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument bol uspesne podpisany..
        /// </summary>
        internal static string successSignDocumet {
            get {
                return ResourceManager.GetString("successSignDocumet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument bol úspešne nahraný.
        /// </summary>
        internal static string successUploadDocument {
            get {
                return ResourceManager.GetString("successUploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prebieha nahrávanie dokumentu na server.
        /// </summary>
        internal static string uploadDocument {
            get {
                return ResourceManager.GetString("uploadDocument", resourceCulture);
            }
        }
    }
}
